name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          # Use pyproject.toml to seed cache; uv.lock may be absent on some branches
          cache-dependency-glob: pyproject.toml

      - name: Install dependencies
        run: |
          uv sync --extra dev

      - name: Ruff Lint
        run: |
          uv run -q ruff check

      - name: Ruff Format Check
        run: |
          uv run -q ruff format --check

      - name: Run tests
        run: |
          uv run -q pytest -q
